- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: /home/rdepaiva/.tmux/plugins
    owner: rdepaiva
    group: rdepaiva
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: /home/rdepaiva/.vim/bundle
    owner: rdepaiva
    group: rdepaiva
    recurse: true

- name: update_menlo_cache_fonts
  command: >
      fc-cache -f -v

- name: install_vundle_plugins
  shell: >
      echo -ne '\n' | vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  sudo: no
  register: resultvim
  failed_when: ( resultvim.rc not in [0,1] )

- name: compile_YCM
  shell: >
     ./install.sh chdir=~/.vim/bundle/YouCompleteMe/
  when: resultvim|success
  sudo: no

