# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/minecraft.yml
  - import_tasks: software/authy.yml

  rescue:
    - set_fact: task_failed=true
