- name: users | rdepaiva | create group
  group:
    name: rdepaiva
    state: present

- name: users | rdepaiva | create user
  user:
    name: rdepaiva
    group: rdepaiva
    groups: adm,{{ sudo_group }}
    state: present
    comment: "Rafael de Paiva Rogerio"
    password: "{{ rdepaiva_password }}"
    shell: /bin/bash

- name: users | rdepaiva | rdepaiva | add sudoers file
  copy:
    src: users/sudoers_rdepaiva
    dest: /etc/sudoers.d/rdepaiva
    owner: root
    group: root
    mode: 0440

- name: users | rdepaiva | create .ssh directory
  file:
    path: /home/rdepaiva/{{ item.dir }}
    state: directory
    owner: rdepaiva
    group: rdepaiva
    mode: 0700
  with_items:
    - { dir: '.bash' }
    - { dir: '.ssh' }
    - { dir: '.tmux/ressurect' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/bundle' }
    - { dir: '.vim/undodir' }
    - { dir: '.config/systemd/user/' }
    - { dir: 'Games' }

- name: users | rdepaiva | add public key
  authorized_key:
    user: rdepaiva
    key: "{{ item }}"
  with_file:
    - users/rdepaiva/ssh/id_rsa.pub
    - users/rdepaiva/ssh/id_ed25519.pub

- name: users | rdepaiva | copy tmux config (workstation version)
  copy:
    src: users/rdepaiva/tmux/tmux.conf.workstation
    dest: /home/rdepaiva/.tmux.conf
    owner: rdepaiva
    group: rdepaiva
    mode: 0600

- name: users | rdepaiva | clone Menlo powerline fonts
  git:
    repo: https://github.com/abertsch/Menlo-for-Powerline
    dest: /home/rdepaiva/.fonts/
    force: yes
  notify: update_menlo_cache_fonts

- name: users | rdepaiva | clone tmux-tpm plugin repository
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /home/rdepaiva/.tmux/plugins/tpm
    force: yes
  notify: update_tmux_plugin_perms

- name: users | rdepaiva | clone tmux-sensible plugin repository
  git:
    repo: https://github.com/tmux-plugins/tmux-sensible.git
    dest: /home/rdepaiva/.tmux/plugins/tmux-sensible
    force: yes
  notify: update_tmux_plugin_perms

- name: users | rdepaiva | clone tmux-continuum plugin repository
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: /home/rdepaiva/.tmux/plugins/tmux-continuum
    force: yes
  notify: update_tmux_plugin_perms

- name: users | rdepaiva | clone tmux-resurrect plugin repository
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: /home/rdepaiva/.tmux/plugins/resurrect
    force: yes
  notify: update_tmux_plugin_perms
  # Vim
- name: users | rdepaiva | vim Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: /home/rdepaiva/.vim/bundle/Vundle.vim
    force: yes
  notify: update_vim_bundle_perms
      #- compile_YCM

  # fzf
- name: users | rdepaiva | Fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /home/rdepaiva/.fzf
    force: yes
  notify: install_fzf

- name: users | rdepaiva | copy dotfiles
  copy:
    src: users/rdepaiva/{{ item.src }}
    dest: /home/rdepaiva/{{ item.dest }}
    owner: rdepaiva
    group: rdepaiva
    mode: 0600
  with_items:
    - { src: 'bash/bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash/bash_profile', dest: '.bash_profile' }
    - { src: 'bash/bash_prompt', dest: '.bash/bash_prompt' }
    - { src: 'bash/bash_functions', dest: '.bash/bash_functions' }
    - { src: 'git/gitconfig', dest: '.gitconfig' }
    - { src: 'git/gitignore', dest: '.gitignore' }
    - { src: 'terraform/terraformrc', dest: '.terraformrc' }
    - { src: 'tmate/tmate.conf', dest: '.tmate.conf' }
    - { src: 'speedswapper', dest: '.speedswapper' }
    - { src: 'bash/bashrc', dest: '.bashrc' }
    - { src: 'bash/profile', dest: '.profile' }
    - { src: 'vim/vimrc', dest: '.vimrc' }
    - { src: 'ssh/config', dest: '.ssh/config' }

- name: Check if vundle is in place
  stat:
    path: /home/rdepaiva/.vim/bundle/Vundle.vim
  register: stat_result

- name: users | rdepaiva | copy vim color files
  copy:
    src: users/rdepaiva/vim/colors/{{ item.src }}
    dest: /home/rdepaiva/.vim/colors/{{ item.src }}
    owner: rdepaiva
    group: rdepaiva
    mode: 0600
  when: stat_result.stat.exists
  with_items:
    - { src: 'gruvbox.vim' }
    - { src: 'solarized.vim' }
    - { src: 'spacegray.vim' }
  notify:
    - install_vundle_plugins
    - compile_YCM
