- name: system setup | development packages | install packages
  tags: dev,development,packages,python
  package:
    name:
      - git
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
    state: latest
