- name: install sunshine requirements
  package:
    name:
      - cmake
      - libssl-dev
      - libavdevice-dev
      - libboost-thread-dev
      - libboost-filesystem-dev
      - libboost-log-dev
      - libpulse-dev
      - libopus-dev
      - libxtst-dev
      - libx11-dev
      - libxfixes-dev
      - libevdev-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
  when: sunshine is defined and sunshine == true

- name: Clone sunshine repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/loki-47-6F-64/sunshine.git
    clone: yes
    recursive: yes
    track_submodules: yes
    dest: /home/rdepaiva/Games/sunshine
  when: sunshine is defined and sunshine == true

- name: sunshine setup | putting script in place
  template:
      src: sunshine.sh.j2
      dest: /tmp/sunshine.sh
  when: sunshine is defined and sunshine == true

- name: sunshine setup | copying config files
  copy:
    src: ansible_setup/{{ item.src }}
    dest: /home/rdepaiva/Games/sunshine/{{ item.src }}
  when: stat_result.stat.exists
  with_items:
    - { src: 'sunshine.conf' }
    - { src: 'sunshine.service' }
  when: sunshine is defined and sunshine == true

- name: sunshine setup | compiling sunshine
  command: bash /tmp/sunshine.sh
  when: sunshine is defined and sunshine == true

