- name: install sunshine requirements
  package:
    name:
      - cmake
      - libssl-dev
      - libavdevice-dev
      - libboost-thread-dev
      - libboost-filesystem-dev
      - libboost-log-dev
      - libpulse-dev
      - libopus-dev
      - libxtst-dev
      - libx11-dev
      - libxfixes-dev
      - libevdev-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
  when: sunshine is defined and sunshine == true

- name: Clone sunshine repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/loki-47-6F-64/sunshine.git
    clone: yes
    recursive: yes
    update: no
    track_submodules: yes
    dest: /home/rdepaiva/Games/sunshine
  become: false
  when: sunshine is defined and sunshine == true

- name: sunshine setup | adding submodules
  shell: git submodule update --init --recursive --depth 50
  args:
      chdir: /home/rdepaiva/Games/sunshine

- name: sunshine setup | putting script in place
  template:
      src: sunshine.sh.j2
      dest: /tmp/sunshine.sh
  when: sunshine is defined and sunshine == true

- name: sunshine setup | copying config files
  copy:
    src: sunshine/{{ item.src }}
    dest: /home/rdepaiva/{{ item.dest }}
    owner: rdepaiva
    group: rdepaiva
    mode: 0600
  with_items:
    - { src: 'sunshine.service', dest: '.config/systemd/user/sunshine.service' }
  when: sunshine is defined and sunshine == true

- name: sunshine setup | compiling sunshine
  command: bash /tmp/sunshine.sh
  become: false
  when: sunshine is defined and sunshine == true

- name: sunshine setup | copying config files
  copy:
    src: sunshine/{{ item.src }}
    dest: /home/rdepaiva/Games/sunshine/build/{{ item.src }}
  when: stat_result.stat.exists
  with_items:
    - { src: 'sunshine.conf' }
  when: sunshine is defined and sunshine == true

- name: sunshine setup | starting sunshine service
  command: systemctl --user start sunshine
  become: false
  when: sunshine is defined and sunshine == true
