# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/rdepaiva.yml
  - import_tasks: users/ansible.yml

  # Set up the ansible environment
  - import_tasks: users/ansible_setup.yml

  # install software
  - import_tasks: software/packages_utilities.yml
  - import_tasks: software/packages_development.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/openssh.yml

  rescue:
    - set_fact: task_failed=true
