- name: system setup | cron | schedule automatic ansible provisioning
  tags: cron
  cron:
    name: "ansible provision"
    user: ansible
    hour: "{{ ansible_cron_hour | default('*') }}"
    minute: "{{ ansible_cron_minute | default('*/30') }}"
    job: "/usr/local/bin/provision > /dev/null"
